type Time {
	time: Float
}

type Query {
	hello: String
	time: Float
}

type Mutation {
	setTime(time: Float): Time
}

type Subscription {
	timeChanged: Time
}

schema {
	query: Query
	mutation: Mutation
	subscription: Subscription
}
